name: update waka section

on:
  schedule:
    - cron: "15 9-23,0-3 * 9-12,1-6 *"
    - cron: "45 8-20/4,0 * 7-8 *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          
